import Navbar from "./Components/Navbar";
import "./globals.css";
import {Roboto} from  "next/font/google";
import MetaData from "./Metadata";
import Footer from "./Components/Footer";

const roboto = Roboto({
  subsets: ['latin'],
  weight:["500"]
});




export const metadata = {
  title: "Sannith Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MetaData/>
      <body
        className={`${roboto.className} bg-black px-4 py-2 lg:px-20 lg:py-4`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
